//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachment
    {
        public int aid { get; set; }
        public Nullable<int> projectid { get; set; }
        public string afile { get; set; }
    
        public virtual project project { get; set; }
    }
}
