//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceMarket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FreelanceMPEntities : DbContext
    {
        public FreelanceMPEntities()
            : base("name=FreelanceMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<userdetail> userdetails { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<logindetail> logindetails { get; set; }
        public virtual DbSet<attachment> attachments { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<bid> bids { get; set; }
    }
}
