//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.attachments = new HashSet<attachment>();
            this.reviews = new HashSet<review>();
            this.bids = new HashSet<bid>();
        }
    
        public int projectid { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public Nullable<int> clientid { get; set; }
        public Nullable<int> categoryid { get; set; }
        public string skills { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string duration { get; set; }
        public Nullable<System.DateTime> date_of_post { get; set; }
        public string status { get; set; }
    
        public virtual category category { get; set; }
        public virtual userdetail userdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attachment> attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bid> bids { get; set; }
    }
}
