//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int rid { get; set; }
        public Nullable<int> clientid { get; set; }
        public Nullable<int> freelancerid { get; set; }
        public Nullable<int> projectid { get; set; }
        public Nullable<int> ftoc { get; set; }
        public Nullable<int> ctof { get; set; }
    
        public virtual project project { get; set; }
        public virtual userdetail userdetail { get; set; }
        public virtual userdetail userdetail1 { get; set; }
    }
}
