//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userdetail()
        {
            this.projects = new HashSet<project>();
            this.reviews = new HashSet<review>();
            this.reviews1 = new HashSet<review>();
            this.bids = new HashSet<bid>();
        }
    
        public int userid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> date_of_joining { get; set; }
        public string contact { get; set; }
        public string pass { get; set; }
        public Nullable<int> roleid { get; set; }
        public Nullable<int> isverified { get; set; }
    
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> reviews1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bid> bids { get; set; }
    }
}
